== AsciiDoc Package for Sublime Text 2 ==
This is an http://www.methods.co.nz/asciidoc[AsciiDoc] package for http://www.sublimetext.com[Sublime Text 2 editor].

It adds syntax highlighting and snippets for AsciiDoc language to Sublime Text 2 editor.

My work is based on the Christian Zuckschwerdt's https://github.com/zuckschwerdt/asciidoc.tmbundle[AsciiDoc TextMate bundle].

Sublime Text 2 is compatible with Textmate editor for OS X snippets, preferences and languages file. 
However, even though it can recognize the Textmate snippets, some features such as tab completion, shortcut commands do not work out of the box.

My work is to overcome these limitations.

All the files provided here are tested in Windows 7 and OS X Lion. 

=== Installation ===

To install the package, follow these steps:

 - Download the zip containing src files.
 - Extract the files to *AsciiDoc* folder (create this folder if not present already) under:
	- Windows: `%APPDATA%\Sublime Text 2\Packages\`    
	- OS X: `~/Library/Application Support/Sublime Text 2/Packages`
	- Linux: `~/.config/sublime-text-2`
	- Portable Installation: `Sublime Text 2/Data`   
 - Close all instances of Sublime Text 2 editor and relaunch the editor.  

If successful, you should see **AsciiDoc** entry under `View > Syntax` and under `Tools > Snippets`.

**Note**: Snippets may take few seconds to load under Windows.

=== Usage ===

 - Create a new file, save it as `<filename>.asc` or change the syntax to AsciiDoc
 - Start typing AsciiDoc!

[TIP]
===========
Syntax highlighting works best with Twilight theme. 
For other themes, you may have to customize them. 
===========

=== Snippets ===

Snippets can be inserted anywhere by using the menu command `Tools > Snippets > AsciiDoc` or by typing two initial characters and hitting tab to complete.
Few tab completion examples are:

 - Comments (type `// TAB`)
 - Headings (type `h1 TAB` to `h4 TAB` for one-liner versions)
 - Table generation (type `|= TAB`) 
 - Tab expansion for blocks (type `== TAB`)  
 - Sidebar block (type `** TAB`)    

=== Keyboard Shortcuts ===

Keyboard shortcuts let you do some quick formatting such setting the text to bold or italics.
Some examples are:
 
 - Bold (type `ctrl+b`)
 - Italics (type `ctrl+i`)
 - Code (type `ctrl+shift+c`)
 - Double Quotes (type `ctrl+shift+'`)

For a complete list, see https://github.com/mrchief/AsciiDoc.SublimeText2.Package/blob/master/docs/shortcuts.asciidoc[Keyboard shortcuts].

=== Planned Enhancements ===

Following are planned enhancements for the package:

 - Adding Build system to preview as HTML or PDF.
 - Anything else you wanna see! Just add it to the https://github.com/mrchief/AsciiDoc.SublimeText2.Package/issues[issues] list.
                                                   
    

=== Author & Credits ===

Created by Hrusikesh Panda. 

Copy left or right, as you wish.                                         

Credit goes to Christian Zuckschwerdt for his original work on AsciiDoc TextMate bundle.